cfg:
  is_decoder: true
  data:
    batch_size: 64
    unk_freq_threshold: 0.0
    min_workers: 12
    global_diagnoses: false
    repeating_events: true
    path_to_db: /rds/projects/g/gokhalkm-optimal/OPTIMAL_MASTER_DATASET/data/FoundationalModel/cprd.db
    path_to_ds: /rds/projects/g/gokhalkm-optimal/OPTIMAL_MASTER_DATASET/data/FoundationalModel/PreTrain/
    meta_information_path: /rds/projects/g/gokhalkm-optimal/OPTIMAL_MASTER_DATASET/data/FoundationalModel/PreTrain/meta_information_QuantJenny.pickle
    subsample_training: null
  experiment:
    type: pre-train
    project_name: SurvivEHR
    run_id: TransformerMLP
    fine_tune_id: null
    notes: null
    tags: null
    train: false
    test: true
    verbose: true
    seed: 1337
    log: false
    log_dir: /rds/projects/s/subramaa-mum-predict/CharlesGadd_Oxford/FoundationModelOutput/
    ckpt_dir: /rds/projects/s/subramaa-mum-predict/CharlesGadd_Oxford/FoundationModelOutput/checkpoints/
  fine_tuning:
    fine_tune_outcomes: null
    custom_outcome_method:
      _target_: null
    custom_stratification_method:
      _target_: null
    use_callbacks:
      hidden_embedding: true
      performance_metrics: true
      rmst: false
    head:
      surv_weight: 1
      value_weight: 0
      learning_rate: 0.0005
  optim:
    num_epochs: 1
    learning_rate: 0.0003
    scheduler_warmup: true
    scheduler: decaycawarmrestarts
    scheduler_periods: 10000
    learning_rate_decay: 0.8
    val_check_interval: 2500
    early_stop: true
    early_stop_patience: 30
    log_every_n_steps: 20
    limit_val_batches: 0.025
    limit_test_batches: null
    accumulate_grad_batches: 1
  transformer:
    block_type: Neo
    block_size: 256
    n_layer: 6
    n_head: 6
    n_embd: 384
    layer_norm_bias: false
    attention_type: global
    bias: true
    dropout: 0.0
    attention_dropout: 0.0
    resid_dropout: 0.0
    private_heads: 0
    use_fine_tune_adapter: false
    adapter_dim: 8
  head:
    SurvLayer: cr
    surv_weight: 1
    tokens_for_univariate_regression:
    - 84
    - 86
    - 107
    - 154
    - 42
    - 231
    - 63
    - 85
    - 247
    - 51
    - 103
    - 146
    - 66
    - 172
    - 152
    - 261
    - 235
    - 193
    - 184
    - 101
    - 223
    - 135
    - 226
    - 202
    - 145
    - 244
    - 165
    - 64
    - 185
    - 238
    - 220
    - 232
    - 240
    - 237
    - 17
    - 239
    - 217
    - 118
    - 219
    - 251
    - 25
    - 150
    - 111
    - 102
    - 15
    - 110
    - 130
    - 128
    - 122
    - 99
    - 77
    - 96
    - 140
    - 50
    - 80
    - 108
    - 138
    - 27
    - 139
    - 125
    - 117
    - 105
    - 109
    - 243
    - 236
    - 208
    - 98
    - 176
    - 209
    - 194
    - 61
    - 73
    - 214
    - 206
    - 229
    - 225
    - 183
    - 186
    - 215
    - 187
    - 248
    - 179
    - 163
    - 180
    - 181
    - 153
    - 245
    - 54
    - 246
    - 112
    - 212
    - 141
    - 204
    - 227
    - 173
    - 55
    - 119
    - 262
    - 127
    - 71
    - 59
    - 144
    - 113
    - 170
    - 241
    - 168
    - 47
    - 159
    value_weight: 0.1
  static: false
vocab_size: 265
hidden_dims:
- 256
- 128
